// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Network string

const (
	NetworkETHEREUM Network = "ETHEREUM"
	NetworkSOLANA   Network = "SOLANA"
)

func (e *Network) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Network(s)
	case string:
		*e = Network(s)
	default:
		return fmt.Errorf("unsupported scan type for Network: %T", src)
	}
	return nil
}

type NullNetwork struct {
	Network Network `json:"network"`
	Valid   bool    `json:"valid"` // Valid is true if Network is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNetwork) Scan(value interface{}) error {
	if value == nil {
		ns.Network, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Network.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNetwork) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Network), nil
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         *string            `json:"name"`
	UserName     *string            `json:"user_name"`
	EmailAddress *string            `json:"email_address"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Wallet struct {
	ID        uuid.UUID          `json:"id"`
	Address   string             `json:"address"`
	Network   Network            `json:"network"`
	Owner     uuid.UUID          `json:"owner"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
