// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, user_name, email_address)
VALUES ($1, $2, $3) RETURNING id, name, user_name, email_address, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name         *string `json:"name"`
	UserName     *string `json:"user_name"`
	EmailAddress *string `json:"email_address"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.UserName, arg.EmailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserName,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE ID = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, user_name, email_address, created_at, updated_at, deleted_at FROM users
WHERE email_address = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, emailAddress *string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, emailAddress)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserName,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, user_name, email_address, created_at, updated_at, deleted_at FROM users
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserName,
		&i.EmailAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, user_name, email_address, created_at, updated_at, deleted_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserName,
			&i.EmailAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
