// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (address, network, owner)
VALUES ($1, $2, $3) RETURNING id, address, network, owner, created_at, updated_at, deleted_at
`

type CreateWalletParams struct {
	Address string    `json:"address"`
	Network Network   `json:"network"`
	Owner   uuid.UUID `json:"owner"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.Address, arg.Network, arg.Owner)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Network,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE ID = $1
`

func (q *Queries) DeleteWallet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWallet, id)
	return err
}

const findWalletByAddress = `-- name: FindWalletByAddress :one
SELECT id, address, network, owner, created_at, updated_at, deleted_at FROM wallets
WHERE address = $1 LIMIT 1
`

func (q *Queries) FindWalletByAddress(ctx context.Context, address string) (Wallet, error) {
	row := q.db.QueryRow(ctx, findWalletByAddress, address)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Network,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findWalletsByOwner = `-- name: FindWalletsByOwner :many
SELECT id, address, network, owner, created_at, updated_at, deleted_at FROM wallets
WHERE owner = $1
`

func (q *Queries) FindWalletsByOwner(ctx context.Context, owner uuid.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, findWalletsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Network,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWallet = `-- name: GetWallet :one
SELECT id, address, network, owner, created_at, updated_at, deleted_at FROM wallets
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Network,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
